### ISSUE TITLE
Estilado

### ISSUE THREAD

**Issue by maxpipoka** [francovillarruel/misiotronica#1]
Hola Franco, estuve revisando tu proyecto. Esta bueno

En el inicio fijate que al ponerlo en movil me aparece corrido a un costado el texto. Te paso captura.
[https://prnt.sc/FgIME-ZfJSW5
](https://prnt.sc/FgIME-ZfJSW5
)
El menú no me aparece y debería hacerse mas chico el icono del carrito.
[https://prnt.sc/Mc27j-bIzfFg
](https://prnt.sc/Mc27j-bIzfFg
)

Al hacer clic en uno producto de la tienda me envia al home. Es así eso?

Muy buena la implementación de la tienda y el carrito.

**Comment by francovillarruel** [comment]
Hola Martin, gracias.. me alegro que te guste

arregle lo del texto en Sobre Nosotros e Inicio

arregle el Menu, es un menu hamburguesa desde el inicio, al darle click se abre y queda normal, y al minimizar la pagina hasta los 800px se hace lateral, y el carrito siempre esta en la barra superior, le quite un poco de tamaño tambien.


la subi en Netlify
https://misiotronica.netlify.app/
pero no se puede ver el componente cuando se escribe mal una url, sale la pantalla de Netlify

**Comment by maxpipoka** [comment]
Ok Franco. Al revisar el repo despues cierro el issue. 
Saludos

**Comment by francovillarruel** [comment]
Hola Martin
Sabes que encontré otra cosa que arreglar que no me marcaste en el issue,
pero la encontré de después del comité

No sé si estoy a tiempo de poder arreglarlo, es que cuando estoy desde el
cel , en el carrito están desalineado el icono de borrar

**Comment by maxpipoka** [comment]
Metele si, lo que quieras mejorar. Tene cuidado de no romper nada nomas, hace una rama nueva por las dudas y trabaja sobre esa. Si despues esta todo bien las juntas.

**Comment by maxpipoka** [comment]
Incidencias solucionadas.
